### ISSUE TITLE
[BUG] 허스키 고장

### ISSUE THREAD

**Issue by javascriptbiggosoo** [mementai-internship/workswave-frontend#125]
## 😱어떤 버그인가요?

> 어떤 버그인지 간결하게 설명해주세요
## 🤔어떤 상황에서 발생한 버그인가요?
커밋시 프리티어 적용안됨 및 npm run prepare 고장

> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요
## 📄참고할 만한 자료(선택)

**Comment by sjlim32** [comment]
😭
